name: Build and Push Docker Image
on: [push]  # 触发条件：代码推送时自动运行

env:
  GIT_CRED: https://${{ secrets.GIT_USER }}:${{ secrets.GIT_TOKEN }}@git.zhyi.cc
  
jobs:
  build-and-push:
    runs-on: 1panel
    container: hub.zhyi.cc/catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug Environment Variables
        run: |
          echo "Checking environment variables..."
          env

      - name: Login to Docker Hub
        run: |
          echo "Logging into Docker Hub..."
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin || exit 1
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to Aliyun ACR
        run: |
          echo "Logging into Aliyun ACR..."
          echo "$ALIYUN_ACR_PASSWORD" | docker login -u "$ALIYUN_ACR_USERNAME" registry.cn-hangzhou.aliyuncs.com --password-stdin || exit 1
        env:
          ALIYUN_ACR_USERNAME: ${{ secrets.ALIYUN_ACR_USERNAME }}
          ALIYUN_ACR_PASSWORD: ${{ secrets.ALIYUN_ACR_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mhcb12_dev:${{ github.sha }} -t ${{ secrets.DOCKERHUB_USERNAME }}/mhcb12_dev:latest . || exit 1
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mhcb12_dev:${{ github.sha }} registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_ACR_NAMESPACE }}/mhcb12_dev:${{ github.sha }} || exit 1
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mhcb12_dev:${{ github.sha }} registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_ACR_NAMESPACE }}/mhcb12_dev:latest || exit 1

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mhcb12_dev:${{ github.sha }} || exit 1
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mhcb12_dev:latest || exit 1

      - name: Push to Aliyun ACR
        run: |
          docker push registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_ACR_NAMESPACE }}/mhcb12_dev:${{ github.sha }} || exit 1
          docker push registry.cn-hangzhou.aliyunc