name: Build and Push Docker Image
on: [push]  # 触发条件：代码推送时自动运行

env:
  GIT_CRED: https://${{ secrets.GIT_USER }}:${{ secrets.GIT_TOKEN }}@git.zhyi.cc
  
jobs:
  build-and-push:
    runs-on: 1panel
    container: hub.zhyi.cc/catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug Environment Variables
        run: |
          echo "Checking environment variables..."
          env

      # 登录到 Docker Hub（或其他 Docker 注册表）
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          # 从 GitHub Secrets 获取 Docker 用户名
          
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # 从 GitHub Secrets 获取 Docker 密码
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to Aliyun ACR
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_ACR_USERNAME }}
          password: ${{ secrets.ALIYUN_ACR_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mhcb12_dev:latest . || exit 1
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mhcb12_dev:latest registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_ACR_NAMESPACE }}/mhcb12_dev:latest || exit 1

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mhcb12_dev:latest || exit 1

      - name: Push to Aliyun ACR
        run: |
          docker push registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_ACR_NAMESPACE }}/mhcb12_dev:latest || exit 1